create table if not exists public.department_feed_reactions (
  reaction_id bigint generated by default as identity primary key,
  post_id bigint not null references public.department_feed_posts(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  unique (post_id, user_id)
);

create index if not exists department_feed_reactions_post_idx
  on public.department_feed_reactions (post_id);

create index if not exists department_feed_reactions_user_idx
  on public.department_feed_reactions (user_id);

alter table public.department_feed_reactions enable row level security;

drop policy if exists "department_feed_reactions_select_public" on public.department_feed_reactions;
create policy "department_feed_reactions_select_public"
on public.department_feed_reactions for select
using (true);
