create table if not exists public.department_feed_posts (
  id bigint generated by default as identity primary key,
  uploader uuid not null references public.users(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  title text not null,
  content text not null,
  category text not null,
  location text not null
);

create index if not exists department_feed_posts_created_idx
  on public.department_feed_posts (created_at desc);

create index if not exists department_feed_posts_category_created_idx
  on public.department_feed_posts (category, created_at desc);

alter table public.department_feed_posts enable row level security;

drop policy if exists "department_feed_posts_select_public" on public.department_feed_posts;
create policy "department_feed_posts_select_public"
on public.department_feed_posts for select
using (true);

do $$
begin
  begin
    alter publication supabase_realtime add table public.department_feed_posts;
  exception when duplicate_object or undefined_object then null;
  end;
end $$;
