create table if not exists public.department_feed_comment (
  comment_id bigint generated by default as identity primary key,
  post_id bigint not null references public.department_feed_posts(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  user_name text not null,
  created_at timestamptz not null default timezone('utc', now()),
  comment text not null
);

create index if not exists department_feed_comment_post_idx
  on public.department_feed_comment (post_id, created_at desc);

create index if not exists department_feed_comment_user_idx
  on public.department_feed_comment (user_id);

alter table public.department_feed_comment enable row level security;

drop policy if exists "department_feed_comment_select_public" on public.department_feed_comment;
create policy "department_feed_comment_select_public"
on public.department_feed_comment for select
using (true);

alter publication supabase_realtime add table public.department_feed_comment;
